### ISSUE TITLE
a 2.0 release?

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#311]
with the merge of #310, we would be changing sgc catlas building. so maybe we should make a 2.0 release?

a few thoughts on what would be nice for that --

- [x] fix #299 bug with missing k-mers
- [x] paired reads #284 
- [x] switch to click interface introduced in #287 for CLI / remove current CLI
- [x] fix `init` command in the click interface
- [x] maybe #217 use threads in Snakefile
- [x] update to sourmash 4.0 when it's out, too
- [ ] conda install - dependent on a few things, unfortunately

**Comment by ctb** [comment]
oh, and probably update to sourmash 3.5.x/4.0-readiness, since I hope that will be released soon-ish.

**Comment by ctb** [comment]
cleanup environment.yml and installation suggestions....

**Comment by ctb** [comment]
while I'm at it, I should release *current* buggy `latest` as v1.3, first.

**Comment by ctb** [comment]
also #340

**Comment by ctb** [comment]
Maybe once https://github.com/spacegraphcats/spacegraphcats/pull/394 and #392 are merged, we should release 2.0. It will then be pip-installable, tho not yet conda installable. @taylorreiter thoughts?

**Comment by taylorreiter** [comment]
Yes that would be great!
#392 is almost ready for review. I’ll wrap it up in the next few days and
make an issue for anything outstanding.

**Comment by ctb** [comment]
before 2.0, we could try to get https://github.com/spacegraphcats/spacegraphcats/issues/347, https://github.com/spacegraphcats/spacegraphcats/issues/374, and https://github.com/spacegraphcats/spacegraphcats/issues/320 in, all of which change formats or output file locations.

**Comment by ctb** [comment]
I ran sgc with https://github.com/spacegraphcats/spacegraphcats/pull/406 and https://github.com/spacegraphcats/spacegraphcats/pull/407 on the hu-s1 data set, in this PR: https://github.com/ctb/2020-rerun-hu-s1/pull/1. It completed, so that's good :). Still need to evaluate results.

Update: results evaluated. All is well.

**Comment by ctb** [comment]
also, need to double check dory and twofoo repos, and maybe make their workflows github action-able.

**Comment by ctb** [comment]
- [x] update pypi stuff - README, and flair on README
